service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-3
  environment:
    MONGO_URI: ${file(.env.json):MONGO_URI}
    TOKEN_KEY: ${file(.env.json):TOKEN_KEY}
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}