on:
  push:
    branches:
    - Mongo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependecies
      run: npm ci
    - name: Create .env file
      run: | 
        echo "${{ secrets.ENV }}" >> .env
        cat .env
    - name: Create .env.json file
      run: |
        touch .env.json
        echo '${{ secrets.ENV_JSON }}' >> .env.json
        cat .env.json
    - name: Create .aws/config file
      run: |
        mkdir .aws
        cd ./.aws
        echo "${{ secrets.AWS_CONFIG }}" > config
        cat config
        cd ..
    - name: Build app
      run: npm run build
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}